language: python

sudo: false

os:
    - linux

matrix:

    # Don't wait for allowed failures
    #fast_finish: true

    include:
        - python: 3.6
          env: MAIN_CMD='pytest --cov changebot changebot' CONDA_DEPENDENCIES="pytest pytest-cov coverage requests flask cryptography python-dateutil yaml pyyaml" PIP_DEPENDENCIES="coveralls flask-dance pygithub humanize"

        # Do a PEP8 test with flake8
        - python: 3.6
          env: MAIN_CMD='pytest --flake8 changebot' CONDA_DEPENDENCIES="pytest pytest-flake8 requests flask cryptography python-dateutil yaml pyyaml" PIP_DEPENDENCIES="flask-dance pygithub humanize"

    #allow_failures:
    #    - env: MAIN_CMD='pytest --flake8 changebot'

install:
    - git clone git://github.com/astropy/ci-helpers.git
    - source ci-helpers/travis/setup_conda.sh

script:
    - $MAIN_CMD

after_success:
    - if [[ $MAIN_CMD == *--cov* ]]; then coveralls; fi;
